In [1]:
data = open('./data/shakespeare_train.txt').read()
data

"First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou are all resolved rather to die than to famish?\n\nAll:\nResolved. resolved.\n\nFirst Citizen:\nFirst, you know Caius Marcius is chief enemy to the people.\n\nAll:\nWe know't, we know't.\n\nFirst Citizen:\nLet us kill him, and we'll have corn at our own price.\nIs't a verdict?\n\nAll:\nNo more talking on't; let it be done: away, away!\n\nSecond Citizen:\nOne word, good citizens.\n\nFirst Citizen:\nWe are accounted poor citizens, the patricians good.\nWhat authority surfeits on would relieve us: if they\nwould yield us but the superfluity, while it were\nwholesome, we might guess they relieved us humanely;\nbut they think we are too dear: the leanness that\nafflicts us, the object of our misery, is as an\ninventory to particularise their abundance; our\nsufferance is a gain to them Let us revenge this with\nour pikes, ere we become rakes: for the gods know I\nspeak this in hunger 

In [2]:
chars = sorted(set(data))

In [4]:
char_to_idx = {char: i for i, char in enumerate(chars)}

In [3]:
MAX_LENGTH = 30

chunks = [data[i:i+MAX_LENGTH] for i in range(0, len(data), MAX_LENGTH)]
chunks[0]

'First Citizen:\nBefore we proce'

In [6]:
import torch
import torch.nn.functional as F

temp = F.one_hot(torch.tensor([16, 44, 53, 54, 55, 1, 13, 44, 55, 44, 61, 40, 49, 8, 0, 12, 40, 41, 50, 53, 40, 1, 58, 40, 1, 51, 53, 50, 38]), num_classes=100)

temp

tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]])

In [7]:
from dataset import Shakespeare
from torch.utils.data import DataLoader

data = Shakespeare(input_file='./data/shakespeare_train.txt')
data_loader = DataLoader(dataset=data, batch_size=64, shuffle=False)

In [8]:
batch = next(iter(data_loader))

In [11]:
input, target = batch

In [15]:
input.size()

torch.Size([64, 29])

In [34]:
from model import CharRNN, CharLSTM
from torch.utils.data import SubsetRandomSampler

sampler = SubsetRandomSampler(indices=[1,2,3])
data_loader = DataLoader(dataset=data, batch_size=64, sampler=sampler)

In [35]:
batch = next(iter(data_loader))
input, target = batch

In [36]:
input

tensor([[55, 44, 61, 40, 49,  8,  0, 34, 50, 56,  1, 36, 53, 40,  1, 36, 47, 47,
          1, 53, 40, 54, 50, 47, 57, 40, 39,  1, 53],
        [ 0,  0, 11, 47, 47,  8,  0, 29, 51, 40, 36, 46,  5,  1, 54, 51, 40, 36,
         46,  7,  0,  0, 16, 44, 53, 54, 55,  1, 13],
        [40, 39,  1, 36, 49, 60,  1, 41, 56, 53, 55, 43, 40, 53,  5,  1, 43, 40,
         36, 53,  1, 48, 40,  1, 54, 51, 40, 36, 46]])

In [33]:
input

tensor([[40, 39,  1, 36, 49, 60,  1, 41, 56, 53, 55, 43, 40, 53,  5,  1, 43, 40,
         36, 53,  1, 48, 40,  1, 54, 51, 40, 36, 46],
        [55, 44, 61, 40, 49,  8,  0, 34, 50, 56,  1, 36, 53, 40,  1, 36, 47, 47,
          1, 53, 40, 54, 50, 47, 57, 40, 39,  1, 53],
        [ 0,  0, 11, 47, 47,  8,  0, 29, 51, 40, 36, 46,  5,  1, 54, 51, 40, 36,
         46,  7,  0,  0, 16, 44, 53, 54, 55,  1, 13]])

In [44]:
import numpy as np

temp = [1,2,3]
np.random.shuffle(temp)
temp

[2, 1, 3]